 
  
   
 
      
         
             
              
//--------------------------------------------------------------------------- ---     
// <auto-generated>            
//     此代码由T4模板自动生成          
//	   生成时间 2018-03-02 10:56:50 by Rex             
//     对此文件的更改可能会导致不正确的行为，并且如果               
//     重新生成代码，这些更改将会丢失。                     
// </auto-generated>      
//------------------------------------------------------------------------------          
    
using System;                
using Microsoft.EntityFrameworkCore;     
using System.ComponentModel.DataAnnotations;    
using System.Collections.Generic;
using CHIS;
using CHIS.Models; 
using System.Linq;
namespace CHIS   
{	   
public partial class MyConfigNames
{
	
	/// <summary>
	/// 健康会员档案 允许修改会员资料
	/// 
	/// </summary>
	public static readonly string UserDocs_CRUD_IsMod =
		"FUNCDETAIL|bool|UserDocs|CRUD|IsMod|1";

	
	/// <summary>
	/// 健康会员档案 允许新增会员资料
	/// 
	/// </summary>
	public static readonly string UserDocs_CRUD_IsNew =
		"FUNCDETAIL|bool|UserDocs|CRUD|IsNew|2";

	
	/// <summary>
	/// 健康会员档案 允许删除会员
	/// 
	/// </summary>
	public static readonly string UserDocs_CRUD_IsDel =
		"FUNCDETAIL|bool|UserDocs|CRUD|IsDel|3";

	
	/// <summary>
	/// 药品档案 新增药品档案
	/// 
	/// </summary>
	public static readonly string DrugArchives_CRUD_IsNew =
		"FUNCDETAIL|bool|DrugArchives|CRUD|IsNew|4";

	
	/// <summary>
	/// 药品档案 修改药品档案
	/// 
	/// </summary>
	public static readonly string DrugArchives_CRUD_IsMod =
		"FUNCDETAIL|bool|DrugArchives|CRUD|IsMod|5";

	
	/// <summary>
	/// 药品档案 删除药品档案
	/// 
	/// </summary>
	public static readonly string DrugArchives_CRUD_IsDel =
		"FUNCDETAIL|bool|DrugArchives|CRUD|IsDel|6";

	
	/// <summary>
	/// 医生档案 允许设置医生的权限
	/// 
	/// </summary>
	public static readonly string DoctorDocument_ACCESS_IsAllowedToSetDoctorAccess =
		"FUNCDETAIL|bool|DoctorDocument|ACCESS|IsAllowedToSetDoctorAccess|8";

	
	/// <summary>
	/// 医生档案 允许搜索时忽略工作站限制
	/// 
	/// </summary>
	public static readonly string DoctorDocument_CRUD_IsAllowedSearchIgnoreStation =
		"FUNCDETAIL|bool|DoctorDocument|CRUD|IsAllowedSearchIgnoreStation|9";

	
	/// <summary>
	/// 库存 是否允许调整库存价格
	/// 
	/// </summary>
	public static readonly string MyPharmacy_StockMonitor_MYSTOCK_IsSetPrice =
		"FUNCDETAIL|bool|MyPharmacy_StockMonitor|MYSTOCK|IsSetPrice|10";

	
	/// <summary>
	/// 药品档案 是否允许药品审批
	/// 
	/// </summary>
	public static readonly string DrugArchives_CMD_IsDrugAllow =
		"FUNCDETAIL|bool|DrugArchives|CMD|IsDrugAllow|11";

	
	/// <summary>
	/// 医生档案 修改医生信息
	/// 
	/// </summary>
	public static readonly string DoctorDocument_DoctorDocs_IsMod =
		"FUNCDETAIL|bool|DoctorDocument|DoctorDocs|IsMod|12";

	
	/// <summary>
	/// 医生档案 删除医生
	/// 
	/// </summary>
	public static readonly string DoctorDocument_DoctorDocs_IsDel =
		"FUNCDETAIL|bool|DoctorDocument|DoctorDocs|IsDel|13";

	
	/// <summary>
	/// 库存 删除库存记录
	/// 
	/// </summary>
	public static readonly string MyPharmacy_StockMonitor_MYSTOCK_IsDel =
		"FUNCDETAIL|bool|MyPharmacy_StockMonitor|MYSTOCK|IsDel|14";

	
	/// <summary>
	/// 接诊 默认出药单位
	/// 处方开药时候默认的开药单位：拆零-SMALL(默认) ；大单位-BIG；
	/// </summary>
	public static readonly string PationtVisitV20_PRES_DefDrugUnit =
		"FUNCDETAIL|string|PationtVisitV20|PRES|DefDrugUnit|15";

	
	/// <summary>
	/// 库存 编辑基础药品信息
	/// 调整药品基本单位和说明
	/// </summary>
	public static readonly string MyPharmacy_StockMonitor_MYSTOCK_IsEditBaseDrugInfo =
		"FUNCDETAIL|bool|MyPharmacy_StockMonitor|MYSTOCK|IsEditBaseDrugInfo|16";

//public T GetFuncValue<T>(string functionKey,string groupKey,string keyName){
//	return 
//}
}
}


