
//------------------------------------------------------------------------------ 
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-24 15:37:43 by Rex  
//     对此文件的更改可能会导致不正确的行为，并且如果  
//     重新生成代码，这些更改将会丢失。  
// </auto-generated>
//------------------------------------------------------------------------------ 
 
using System;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Ass;
using CHIS.Models;
namespace CHIS.DbContext
{

    public partial class CHISLogEntitiesSqlServer : Microsoft.EntityFrameworkCore.DbContext
    {

        private string _connectionString = null;
        public CHISLogEntitiesSqlServer(string connectionString) : base()
        {
            this._connectionString = connectionString;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!string.IsNullOrEmpty(_connectionString))
            {
                string str = this._connectionString;
                optionsBuilder.UseSqlServer(str);
            }
        }



        public Ass.Data.IDbUtils DbUtils
        {
            get { return new Ass.Data.SqlServerDbUtils(); }
        }

        public virtual DbSet<CHIS_Sys_Logs> CHIS_Sys_Logs { get; set; }
    }
}

namespace CHIS.Models
{
    public partial class CHIS_Sys_Logs
    {
        public long Id { get; set; }
        public string ModeName { get; set; }
        public string ProcedureName { get; set; }
        public string LogType { get; set; }
        public string Msg { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<int> OpId { get; set; }
        public string OpFullName { get; set; }
        public string KeyId { get; set; }
    }
}

